### ISSUE TITLE
Could not find imported module support code for artifactory_repo.  Looked for either artifactory.py or module_utils.py

### ISSUE THREAD

**Issue by SckyzO** [quadewarren/ansible-role-artifactory#19]
Hello, 

Thank you for your work. I try to use this module, but when I run test playbook, i have this error : 

TASK [create test-local-creation repo] **********************************************************************************************************************************************************
task path: /root/ansible_jira/test.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1592574264.4-207794649637856 `" && echo ansible-tmp-1592574264.4-207794649637856="` echo /root/.ansible/tmp/ansible-tmp-1592574264.4-207794649637856 `" ) && sleep 0'
fatal: [localhost]: FAILED! => {
    "msg": "Could not find imported module support code for artifactory_repo.  Looked for either artifactory.py or module_utils.py"
}

I use Ansible 2.9.9 on CentOS 7. 
But i have the same problem with Ansible 2.8/2.7, and I have an other errror message on Ansible 2.6 : 
TASK [create test-local-creation repo] *****************************************************************************************************************************************************
task path: /root/ansible_jira/arti.yml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1592577155.53-3301470680030 `" && echo ansible-tmp-1592577155.53-3301470680030="` echo /root/.ansible/tmp/ansible-tmp-1592577155.53-3301470680030 `" ) && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 584, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 770, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 165, in _configure_module
    environment=final_environment)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 911, in modify_module
    environment=environment)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 702, in _find_module_utils
    recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 515, in recursive_finder
    msg.append('either %s.py or %s.py' % (py_module_name[-1], py_module_name[-2]))
IndexError: tuple index out of range

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
        to retry, use: --limit @/root/ansible_jira/arti.retry

PLAY RECAP *********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

Have you already see that ?

My workspace is like this : 
playbook-artifactory.yml
roles/
├── ansible_artifactory
│   ├── lib
│   │   └── ansible
│   │       └── module_utils
│   │           └── artifactory.py
│   ├── library
│   │   ├── artifactory_groups.py
│   │   ├── artifactory_permissions.py
│   │   ├── artifactory_replication.py
│   │   ├── artifactory_repo.py
│   │   └── artifactory_users.py
│   ├── meta
│   │   └── main.yml
│   ├── README.md
│   └── tests
│       ├── inventory
│       └── test.yml
[...]

Regard,

**Comment by quadewarren** [comment]
I am sincerely sorry for the late response! Saw this message late last Friday and a busy weekend + sleep made me forget until today. 

I believe when I initially wrote this, the support was for Ansible 2.5, so it's entirely possible some change in 2.6+ caused this error. I originally wrote these modules for the company I work for to consume internally. I will check with them if they are running post 2.5 and I will see what I can do on my end. I'll keep you posted, but you may not get a response until next week.

**Comment by quadewarren** [comment]
Edit: I misread the tree diagram, you can disregard my below comment because it looks like you **DO** have it correct. 

@SckyzO I think I may have discovered your issue while looking over my own installation. I believe you have _artifactory.py_ WITHIN the **module_utils** directory. Additionally, it looks like **module_utils** is not inside the **ansible** directory, where it should be. Those could be your culprits.

My current directory structure is like so:

├── lib
│   └── ansible
│       └── module_utils
│           └── artifactory.py
├── library
│   ├── artifactory_groups.py
│   ├── artifactory_permissions.py
│   ├── artifactory_replication.py
│   ├── artifactory_repo.py
│   ├── artifactory_users.py
├── meta
│   └── main.yml
├── README.md
└── tests
    ├── inventory
    └── test.yml

**Comment by quadewarren** [comment]
@SckyzO 
Just confirmed that my organization is using these artifactory modules with Ansible 2.9.9 . I'm going to have to build out a new virtual environment to see if I can replicate the errors you're experiencing. I'd recommend you look into your pathing to see if there may be any discrepancies there.
